services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service
    ports:
      - "5432:5432"
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        APP_NAME: api
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: db://user:password@db:5432/service
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm turbo dev --filter=api
    depends_on:
      - db
  shell:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        APP_NAME: shell
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: pnpm turbo dev --filter=shell
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
  account:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        APP_NAME: account
    expose:
      - "3000"
    environment:
      - WATCHPACK_POLLING=true
    command: pnpm turbo dev --filter=account
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
  contents:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        APP_NAME: contents
    expose:
      - "3000"
    environment:
      - WATCHPACK_POLLING=true
    command: pnpm turbo dev --filter=contents
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api