import StyleDictionary from 'style-dictionary';

/**
 * Helper: 토큰 이름을 CSS Variable 이름으로 변환
 * 예: theme-light-sys-color-primary -> --sys-color-primary
 */
const formatName = (name) => {
    return name
        .replace(/^theme-light-/, '') // Light 모드 접두사 제거
        .replace(/^theme-dark-/, '')  // Dark 모드 접두사 제거
        .replace(/^primitives-/, 'prim-'); // Primitives 단축
};

const sd = new StyleDictionary({
    source: ['src/tokens/design-tokens.json'],
    hooks: {
        formats: {
            'scss/base-variables': ({ dictionary }) => {
                const primitives = dictionary.allTokens.filter(t => t.path[0] === 'primitives');
                const lightTokens = dictionary.allTokens.filter(t => t.path[0] === 'theme' && t.path[1] === 'light');
                const darkTokens = dictionary.allTokens.filter(t => t.path[0] === 'theme' && t.path[1] === 'dark');

                const formatLine = (token) => `  --${formatName(token.name)}: ${token.value};`;

                return `/**
 * Do not edit directly.
 * Generated by Style Dictionary
 * Base definitions for CSS Custom Properties
 */

:root {
  /* Primitives */
${primitives.map(formatLine).join('\n')}

  /* Semantic (Default/Light) */
${lightTokens.map(formatLine).join('\n')}
}

[data-theme="dark"] {
  /* Semantic (Dark Override) */
${darkTokens.map(formatLine).join('\n')}
}
`;
            },

            // 2. Bridge SCSS: SCSS 변수 매핑 및 Base import
            'scss/bridge-variables': ({ dictionary }) => {
                // Light 토큰만 필터링 (인터페이스 역할)
                const lightTokens = dictionary.allTokens.filter(t => t.path[0] === 'theme' && t.path[1] === 'light');

                // CSS 변수 이름 매핑
                const mappedTokens = lightTokens.map(token => {
                    const name = formatName(token.name);
                    return `$${name}: var(--${name});`;
                }).join('\n');

                return `/**
 * Do not edit directly.
 * Generated by Style Dictionary
 * SCSS Bridge: Maps SCSS variables to CSS Custom Properties
 */

// [Import Requirement] Base SCSS 참조 (CSS 변수 선언 포함)
@use './base';

${mappedTokens}
`;
            }
        }
    },
    platforms: {
        css: {
            transformGroup: 'scss',
            buildPath: 'src/styles/',
            files: [{
                destination: 'base.scss',
                format: 'scss/base-variables'
            }]
        },
        scss: {
            transformGroup: 'scss',
            buildPath: 'src/styles/',
            files: [{
                destination: 'variables.scss',
                format: 'scss/bridge-variables'
            }]
        }
    }
});

(async () => {
    try {
        await sd.cleanAllPlatforms(); // 기존 빌드 파일 정리
        await sd.buildAllPlatforms(); // 새로운 빌드 실행
        console.log('\n✅ Tokens built successfully with Style Dictionary v4!');
    } catch (error) {
        console.error('\n❌ Build failed:', error);
        process.exit(1);
    }
})();