import StyleDictionary from 'style-dictionary';

/**
 * Helper: 토큰 이름을 CSS Variable 이름으로 변환
 * 예: theme-light-sys-color-primary -> --sys-color-primary
 */
const formatName = (name) => {
    return name
        .replace(/^theme-light-/, '') // Light 모드 접두사 제거
        .replace(/^theme-dark-/, '')  // Dark 모드 접두사 제거
        .replace(/^primitives-/, 'prim-'); // Primitives 단축
};

// Style Dictionary 설정 객체 생성
const sd = new StyleDictionary({
    source: ['src/tokens/design-tokens.json'],

    // 1. Hooks: 커스텀 포맷터 등록 (v4 방식)
    hooks: {
        formats: {
            // CSS Variables 생성 (Light/Dark 자동 분기)
            'css/theme-variables': ({ dictionary }) => {
                const primitives = dictionary.allTokens.filter(t => t.path[0] === 'primitives');
                const lightTokens = dictionary.allTokens.filter(t => t.path[0] === 'theme' && t.path[1] === 'light');
                const darkTokens = dictionary.allTokens.filter(t => t.path[0] === 'theme' && t.path[1] === 'dark');

                const formatLine = (token) => `  --${formatName(token.name)}: ${token.value};`;

                return `/**
 * Do not edit directly.
 * Generated by Style Dictionary
 */

:root {
  /* Primitives */
${primitives.map(formatLine).join('\n')}

  /* Semantic (Default/Light) */
${lightTokens.map(formatLine).join('\n')}
}

[data-theme="dark"] {
  /* Semantic (Dark Override) */
${darkTokens.map(formatLine).join('\n')}
}
`;
            },

            // SCSS Bridge 생성 (CSS Variable 참조)
            'scss/bridge': ({ dictionary }) => {
                // Light 토큰만 필터링 (인터페이스 역할)
                const lightTokens = dictionary.allTokens.filter(t => t.path[0] === 'theme' && t.path[1] === 'light');

                return `/**
 * SCSS Bridge
 * Maps SCSS variables to CSS Custom Properties.
 */

${lightTokens.map(token => {
                    const name = formatName(token.name);
                    return `$${name}: var(--${name});`;
                }).join('\n')}
`;
            }
        }
    },

    // 2. Platforms: 변환 설정
    platforms: {
        css: {
            transformGroup: 'scss', // name/cti/kebab 등 기본 변환 포함
            buildPath: 'src/styles/',
            files: [{
                destination: 'base.css',
                format: 'css/theme-variables'
            }]
        },
        scss: {
            transformGroup: 'scss',
            buildPath: 'src/styles/',
            files: [{
                destination: 'variables.scss',
                format: 'scss/bridge'
            }]
        }
    }
});

// 3. Build 실행 (Async)
(async () => {
    try {
        await sd.cleanAllPlatforms(); // 기존 빌드 파일 정리
        await sd.buildAllPlatforms(); // 새로운 빌드 실행
        console.log('\n✅ Tokens built successfully with Style Dictionary v4!');
    } catch (error) {
        console.error('\n❌ Build failed:', error);
        process.exit(1);
    }
})();